services:
  server:
    image: tryton/tryton:${VERSION:-latest}
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - PYTHONPATH=/var/lib/trytond/custom_modules
    ports:
      - "8000:8000"
    volumes:
      - "tryton-data:/var/lib/trytond/db"
      - "./custom_modules:/var/lib/trytond/custom_modules"
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/$${DB_HOSTNAME:=$${POSTGRES_PORT_5432_TCP_ADDR:='postgres'}}/$${DB_PORT:=$${POSTGRES_PORT_5432_TCP_PORT:='5432'}}; do sleep 0.5; done) 2>/dev/null
        echo "${PASSWORD:-admin}" > /tmp/.passwd
        TRYTONPASSFILE=/tmp/.passwd /entrypoint.sh trytond-admin -d "${DB_NAME:-tryton}" --all --email "${EMAIL:-}" -vv
        if command -v uwsgi &>/dev/null; then uwsgi --ini /etc/uwsgi.conf; else gunicorn --config=/etc/gunicorn.conf.py; fi
    depends_on:
      - postgres
  cron:
    image: tryton/tryton:${VERSION:-latest}
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - PYTHONPATH=/var/lib/trytond/custom_modules
    volumes:
      - "tryton-data:/var/lib/trytond/db"
      - "./custom_modules:/var/lib/trytond/custom_modules"
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/tryton/8000; do sleep 0.5; done) 2>/dev/null
        trytond-cron -d "${DB_NAME:-tryton}"
    depends_on:
      - postgres
      - server
  postgres:
    image: postgres:${PG_VERSION:-latest}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-tryton}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
  tryton-data:
